<?php

arch()
    ->coversNothing()
    ->expect('MohammadAlavi\ObjectOrientedJSONSchema')
    ->toOnlyBeUsedIn([
        'MohammadAlavi\LaravelOpenApi',
        'MohammadAlavi\Laragen',
        'MohammadAlavi\ObjectOrientedJSONSchema',
        'MohammadAlavi\ObjectOrientedOpenAPI',
        'Workbench',
    ])->ignoring('JSONSchema/Trash')
    ->and('MohammadAlavi\ObjectOrientedOpenAPI')
    ->toOnlyBeUsedIn([
        'MohammadAlavi\Laragen',
        'MohammadAlavi\LaravelOpenApi',
        'MohammadAlavi\ObjectOrientedOpenAPI',
        'Workbench',
    ])->and('MohammadAlavi\LaravelOpenApi')
    ->toOnlyBeUsedIn([
        'MohammadAlavi\Laragen',
        'MohammadAlavi\LaravelOpenApi',
        'Workbench',
    ]);
