<?php

namespace MohammadAlavi\LaravelOpenApi\Factories;

use MohammadAlavi\ObjectOrientedOpenAPI\Schema\Objects\Info\Info;
use MohammadAlavi\ObjectOrientedOpenAPI\Schema\Objects\OpenAPI\OpenAPI;

final readonly class DefaultFactory extends OpenAPIFactory
{
    public function instance(): OpenAPI
    {
        return OpenAPI::v311(
            Info::create(
                config('app.url', 'http://localhost'),
                '1.0.0',
            )->summary(config('app.name', 'Laravel') . ' API')
                ->description('API documentation generated by Laragen.'),
        );
    }
}
