name: Tests

on:
  push:
    branches:
      - main
      - '*.x'
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_run:
    workflows: [ PHP-CS-Fixer ]
    types:
      - completed

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [ 8.2, 8.3, 8.4 ]
    name: PHP ${{ matrix.php }}
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
      - name: Install Redocly CLI # https://redocly.com/blog/consistent-apis-redocly-github-actions
        run: npm install -g @redocly/cli@latest

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          tools: composer:v2

      - name: Setup Composer token
        run: composer config -g github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --optimize-autoloader

      - name: Execute tests
        run: ./vendor/bin/pest --ci

  coverage:
    runs-on: ubuntu-latest
    needs: tests
    name: Coverage
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
      - name: Install Redocly CLI # https://redocly.com/blog/consistent-apis-redocly-github-actions
        run: npm install -g @redocly/cli@latest

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: dom, curl, libxml, mbstring, zip
          tools: composer:v2
          coverage: pcov

      - name: Setup Composer token
        run: composer config -g github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --optimize-autoloader

      - name: Execute tests with coverage
        run: ./vendor/bin/pest --ci --coverage-clover=coverage.xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage.xml
          fail_ci_if_error: true
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}